### ISSUE TITLE
Support for Adafruit PWM servo-controller (PCA9685 i2C chip)

### ISSUE THREAD

**Issue by mano1979** [KurtE/Raspberry_Pi#3]
Can we expect support for the adafruit servo driver? It is nowadays widely used but yet, there is no hexapod script that supports it.

It would be wonderfull if we can have the beautifull motion of the phoenix hexapod, but still use the small sized servo controllers.

My hexapod uses 2 of these servo controllers one for the left (HEX adress 0x41) and one for the right (0x42)

**Comment by mano1979** [comment]
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAQEhUQEhIVFRUVFRUVFxUVFRUVFRUQFRUWFhYVFRUYHSggGBolGxYWITEhJikrLi4uFx8zODMtNygtLisBCgoKDg0OGxAQGy0lICY1NysvLTcrNS0tLS0tLSstLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLi0tLf/AABEIALcBEwMBIgACEQEDEQH/xAAbAAACAgMBAAAAAAAAAAAAAAAAAQIGBAUHA//EAEYQAAIBAwMCBAMEBwYDBgcAAAECEQADIQQSMQVBBhMiUTJhcQcUgZFCkqGxwdHhFiNSU2JjVNLwM0NyotPxJDSCk6Oys//EABkBAQADAQEAAAAAAAAAAAAAAAABAgMEBf/EAC4RAAIBAwIEBQMEAwAAAAAAAAABAgMREiExBBNBURQiMmFxgcHwobHR4UJSkf/aAAwDAQACEQMRAD8A6vTpCnUWAUUU4qQEUGig0ACnQKKAVOlToApCnQBQBRTooAUU6Qp0Ampig0ZoApUZoigAiig06iwEKlFIUZpYAaAKDTFLARFIipGkaWAooinSmgFRTopYCIpCnQKAUU6KdQCIooAoirADTFIinFAFI06KAKdEURQCipRSFOKAKBTikKAdBFFBoAFOlQKADTpU4oApAZpxRQARTpRToCIp0CiKADQKCKBQBSanSNAOg0UqAR5pxSNFAFRqRpCgCKdFFRYi5EU6UU9tSSI06VSC0ARS709tAFAOiKIpxQEUqVJRTigA0lpxRFAOk1OKIigCinFAFARNSiiKe2gFFICpRSFAEURT20RQCFEUAUUAEUlFM0ooApNUopEUAUURRmgInmnFBFOgFUYqWaBzQCiijNFCLiomiKUUJAc1KoinFASpLRQooCVV/ouvd9dr7DfDaOmZDJMrctGeTAgqRiK31xwqljwoJP0Ak/urk3T/ALQbWk1t9r6XfK1FyVYqAbVoxBZRloO+eT+6oe5Jd/v9wdXGm/7ttAboy2Li6jaRE7fhI7TXr4h6k9nV9Ptj4L929bfJGRZLLIBhsg81R+p+O9PY1335Rcu6d0RF2ptJ2h1d1ZgNy+pDE9vnWT4n8eaRrtjU2Ga7asmXKpAJLK+1WYCGGyDwPUPnEX0BcPG/VG0mmF5Zxf06tDbfQ91VOfbOR7E1v4rmHizx5o9VprI0zlnLpcuIUk2rcFWW5ggN6jEH9EmYq6eEPFGn6naN6yHXa210cQytyMgkGRnB71KepBvBVb+z/W3L+gs3Lq7XJuAiCOLrgHOYKwfxre6/UJatszmBx8yzHaoHzJIA+tUHwb4002mA0GuvNb1FvcXuXoW2xgGC84aOxqOpPQsfhXXXLt7Xo4gWtWVQ+r1W9iwck9wRiBj609Lr3PVb2nI9A0lq4DLRuNwqRE7QczgTkfKqx0PxfZ0Wr1FrWM9sam+blh3ACLp2LlDcMygz3FLUeMrOl6hd1N53OjvW7dqzcRAym6hAusCMskgerPGKJ6AtHVdfcTqWisgEpdt6osQWgFEVl3AHbk8E/hzVjrnnX/Ftq3rbGrS4bujtWnW89kLcTznK+WAw5MNkA9xV46Vr7WqspqLLbrdxdytxj2I7EGQR2INSgZdJeaIrX9a6zY0dvzbzFQWVFAUszXHMKqqOSTUkGv8AAnUn1WjW88ybuoGWZjC37ijLZ4A+gxUvDfU3v39ejTFnUi2ssT6fJQ4B+ETmB7mtD4I8WWLWmNjW3hZ1NgXLt1bii2fKa47IVEAN6CmBnIo8H+LbJ1Got37htnUX2vaXzU8oXNL5aQdxAE84OaquhZm703U3PVLulzsXSW7oO5o3G6yn08AxGean1fqrW9fodMJi+NSW9UD+6thhK98n8Kruh8a6U9Re410Lprtq1Zs3mtlUfULcubl80j4cGCTFenW/F+mTqFlhdBs6cX01NwW2dbVx1t+WPMCnuQDBx3qOhBe2rWeJdedNo9RqBM27LuCIkEKYIkETPuK2Vu4rKGVgysAVYEEFSJBBHIiqt9o/XdNptHdtXSjPetOEsmT5sLJnblV/1GBMd6syCx6G/vs27p/Sto5H/iQN/GtZ4Q6sdZorOqMzcBPqCg4dl4XHasTTeMOnDR+f94thEiyVyGF4AL5eyN3PyiM8ZrXeBPFWg+4KPMt2Pu9sPdtkkC0jszLBYDdPynkD2qLkm+8OdX+9Nqhn+41VywJA4RU4jnnvmpaXqu/W39Jn+6s2H4ETcNyczJwBj5Vovs/65pLz6tLTW1Z9VevBdxm7bi2DeAYCAT27VHoXiHRXepak27ts+ba06JdD+m86+b6EnuADwc0uC6GnQRxSg1YgKXenml3oAopZ+VFCoqKNoo20LEKCae3HFY19qAw/EHX7Oit+ZdPOFUfEx9h/OqVf8ddQaDasWran4Rc3ux9pC8flWr+03WbdXZ3epbaoxX3BeSPxC0JqbZtbwxvHcWXZxBM+ruD7it6ilSpRlCOTffZGUfPNpuyRDrH2g9TRXt3LdobldZCN3UzHqwYM5FULxNdYvuLM8py0mMsduewmt74q6yLwI2gOQoIU7tuwN6iexO6I7AGq31LVG4EhI2qFOQdxhc8Y/bWM22otxszSKtfW5l9TvltNp8sdilIJJVeAAonA9Pyp6TVN9xZdzAC5u2TCncB6o98xWNf1RbTqm3KMW3SpkHdjbEjkZJqOm1MWGtFMtBBxiNsj3gx2rMsZXQNURb1IDFdycDhoDCDVi+z/AMXXdFbe1bW3te5vYuGJnbHphh2Sqr0jUhA4dCwZGC8YcmA2fkTxWNfO2yDwTcH7FP8AzVaO7Iex0nxV48u6mx5BW0Fd7W4gMGG26jT8RBGM1zfxMm2/cXByMgQDx2rz0LEy5loZOZP6U/wp9UY3Lm5V524BDRAE5HPE0aa0YR7+Ir25pgQFjHcgc/trGu3D5ajJAAAE4HPA7cUuobmyBMrwCDGBzHHfmvUae4wVApLE/D3xuPHbFToQGk1B8lkBO0ySsnbu3KZK8TXRvDP2h3dFprOmXT22VLRfcbjr6WutyNp/SP7a5tbR0UqywwEEYkGU/lWV1F3RrMEqfIt8Eg5LEz+daUkmys72OvP9pOrWd2jtADk+eY4Y/wCCZhTjnI96p/jXxjc6h5aPZFs2b36Ll5JKHGBxt/bVbOmuZP3qTOCrswZxbZzuJiIWVnOTHvWJpXJQuSSfPtEkmeznP41rVglHRFIN33F4ovm5qGZizEtEvJMCQJJzx70/EXUGvraLydlvyxuYt6ViIngfKsTWuXcNHJn6SDRqyxEAd/8AlrlSRsZN/W3G0y2WZjbRwVQklVZvMkhfnmszpeoddBqEVyEZrZZAYDGUAJH5flWrdjsiP8J/IP8AzrK0mpA0ty2Q25ihEfDClPiz9e1RL2COldL+1u3pdPY0zaVibViym4XFg7bagGNv7K0/iHxYOo6vTahLSpts3FAvFXQiX3FxgR9TXO+rf9p/9Fr/APmtbfo122vkG5OzZcmJmC9wcjP7K0mljoisb33McsPvZaFnzp49IPmE/gJ7V7+Kdv3ppVFIAEIu1fgGQJMTWPbuqdRLceYCTBwu8knFPrd9XvFlO5SBDGZICL75rLqXM/xZsI04Nq2kW1ygILj0jc88tg1tOkXltWdHc8pCF1Vpgwxcco9w7STiM1o+vXrZNsIdwCrJ/wBZbIGBxx+HNZmmvWyulVSd3nJuXECHbaRif0jVV0B1tftb0TEAWb/02oT+ENW16d9oegusEZnssePNTaP1hIH4xXKvB93TW7bM8bmTGCS1wu4b9UBMceue4rbXdOjIitBViZJYnaoUlnz8O3mflGa6JVaSqctxfyZKFTHLJfB2gMDkfn8qXft/GqB9lnVXfRlGYk27hVZkwhVSB9JLYq8Jek8j+NKkMJOJaEso3MmaK8W3diKKoD1pGjaKCMGBQsKMVh6jms5lrBvDNAch8cXbZ6i3m5VBbWIJEhQ0GMxk8e9aHqV7SllK2gRtIZQWQboMGfrHbt9a3HXNVGvvsELEOwEDdG0bZI78e/7orWavqQ3kmyZ2bCG2jO0iSCpOOeQZH4V24vnR0eke+n/DFO0H89vuai+LbEBF8sAPmeTt9G6O+7k+x+VYOu6HrRbYvaYKsMSWUgDgHBz8verQmoS6wttYCrB3NCi4dgFySwQQdqMsCPj+QrK1fUNPdR2a0Ia2pfYRPpa46lpIO7czE5n51NeNNNZCDdtCmnpGrdSRbYgpu3bl27TncTOB8zRoem6tkUpbdlnbK5Ejt+VXV7+mOGBjybemmEWLZKQDDmT6U9RMio6PWaUeUEDgWrzm2Syj1oSzA+ohlLKSCf2Vhaj3Ze8+xSNH03VkFVtuxRyDtG6GxiR3ma9+oaN1RbbCH3uzL3VStsLu9jh8c8cTVrt6jRrZJAugN/8AEYKyVQhhjeoIEA7c5mIqPUbWjZ3uN525irNBtQGuuUXBIMbvrA9zVo8lPdkPN9CrdP0jlHRBLkqVA+IgB9+2OTEY9j3rwv8ASNUfLLW2T1wN/olsYXdEmrrpE0Vi8rq1+Uuqok2yC2zzIMEH4ZnHNes6fbacNcPkC9cTdBVjbuM7B/dQ5A4WR+dS1Rb0YvNLYoes6XqijbrdwAEEl1KKMxy0DvxXvf6frJZdt04+KH2wBz5hER85itxr+s3b4ZWCwzq/p3YK21tjBMHCjtM+1edzqDGwtjau1SWBEySd3MGDljk9gK28Gu5Tms0+m0Or9PoutuEyqs4YE8hgCD+dZ7aFLrhLlwJ5duwkk43AqLiyAcgE/IEZ4NbXousLqNIbashZnJ2uWkLu4Ug/oj9uDWLr9MrXhbEKAp4AxBOIJGeBBg+9YVEqMrIunmjyv9H0jBvLvHcuz4jbh5QFgklQIY/pEcEZMVh3NIVS+tqXKXht2+pmsL5o3gLyPgJPAmvRru5QoX4QZOMj54/6ms3pNoOrTyDIII3D0xiGU9/ePke1ecpaNEqFit/dNUxUi3cMEx6SM4kKIyY7CTFRuaXUsMK5iCfSVjsJMDvH41vuoazzWVgGQBQqqX3lRz8cAnOZMn58R7dV6rc1G3cNoUAAA8kTLHsWz7DGK6fBruZ80rj2r5lNr7s+nbBEcziRgVO211dqMpB9MArnMQRjPbPerfpdWdVbGnZjbW0jO1zcWDIvY28e8zJ+HHNbKxo7YstZGpYG2+4vs1ClE2Aldm4SIAPB+P8AGsZ0YQdpSLqcnsjnvWdO3mnGQtoGezC0gYH5gyD9K9mLW7NomIIYZ7MLlwkfWCD+VWs+HbE7fvgJkiPJYsG27gCoO4GJMEcD51ndH0NrTbn+9+ko0+hlAxhyCSDtmfUIE/nMo0WtJBOXY5994bfvj07RmPTOO4+ZobUElGC4BIbBIx7ntj91X610wJcF59YxgBjKtu8pSNwLSQF7GcUdS6dvuG4dYo2vIOzaEDmBAVvRPtyY71nyqf8AuTlLsc/1WqZllVEgjgTgyc/jFbLpd/detDaDFxI57OJMTVu6l0/7xsUapB6R6fTDXbYCs4VPd/qQWiRgA65bT7vFu4hdbYZyCpa4h2qfUpJIJls/6hJ7TGlBteZByfYqfSQ+9tt9LfrAKvkMMy20gqYjvHNWO1p7l62wfU+iVgIqKr7l3AELkkYBGYJ+k6+1otDjdeK+kSQWeH3EQB5K7gVgziD71k9P0elgnzGg7YG6GBKyVYACdpxuwDmPlrxEcIZJtPulcrS8zs/3Lx9lQ22r6cxdj8lAroWl5HH8fwrnP2ViLeoVSIDiDyPhHtyK6PpO2R/PHauev62Wh6TOC0UFW7Efkf50VkSOkw+U5H/vQFGfnzQV4EYH7MULEmrBvDNZxHetdqyFDHsAW5PbNEDij3bjX77os7nckyFgF27nEeqI+leY1uqV3ZLa4KyCA5UiVnPEhys8Q3bmloLV1wxUoASMvPxE9iufr2rzXR6lzcuL5ZyEufAVAkMu4NgiVHvwK7Y4viZenRfX6mWqpLf7GTb6ldtsv3i3tt+peH3AhCgAJYkDGTnvzW8u+JtJedW8pyE9e3dcIxtJy07VABzGZqmdR1d5pt3Wna7SIXFwlt2QM5qWg6fqHBe0pIO5CQyiRA3LBORBFb1KMJ6yM4ya0Rej1XTecGGnYkAAbC20eYCVZnQQuGXB5B7TU7GutBzcFhyX2pum4JhQ0hgIbdtYzx9a0GjF0eWjW7puLtLlbigNbAdEAi4BI2gdvgP4w1FhgGUW9Sju5KN5qkIBBY4uc7CZk5J5rDwtLb7l85G+s9S0yl2a0fWdzH1QAWAj1KeQ9v8AWB7zXjpddpfVZW05bgtFwwzoCI9ERyQZyDWAtlFCg2rpUqFIc+ZtbzRtB/vCNpK2/SoGWGRmleDqrX1FxLiW3CqNm0zbSXC7mAUbGMEkwFGYEPDUvxjmSM5+oaRk8ry7oA9IY27szuJxNuZMERNefUhp7lm4tnTurm0xUi0FLbrbCNwtKXliDz9citT07S6tgxulhKsATdcOCyErsVW25bbIb54FZOpXUAXHtFidqC2fNutvcXdrkrdaBgH0mR9TNSuHpp3T/Uh1JFR1Gne3h0ZfqCOOY9+R+deROKy+o3r0+XdwUj0wqgSqgYXHwKgHyArALV3IxNp4eQG9krARyd2yPhI/TBHf+or21BH3k/JIj5RiJERB7Y9sRT8LqovkKST5TwQGEMYH6NxTwT7/AE9sfWNF9zKiQASfeBkbe815nFu9T6HVS9I9MBEwPhzETmDJxzU+hD0vH+o9zwvb0Nn5gA/OKwdTf28ENI2yN8gfj/1isvoWFu8fA/8Ah/wP7sv8fp78y3Rc1+xjEAngYBOTMDA55x8qndtMIBUiTGQRnGPrkY+Yr36Z1V7A9Ko3rVxvUmHQOARDCPjNZ9rxRfDbmCt6y4kvKk7DtU7pVfQMDmTXt3ZxtC8LGz5zC+222bZDSBkb0lckDgHkirY+l0TFnZwo5uQAJO07GY+ZuIgL3GIiqN0++5vHaUDXd6EuPQBdlW+nxVZjpNVtuGbezy9o8xSDmyqMwwIwoxkY/E81ehGcsm7GkJtaIzLOj6eS10XQ36RhyYvQoLFvOLhdoIHq7cVI9L6d6vMuqFcBVUlliyZDghLwPYck81qx0rUIl0E2jvQQ1uUYiLnp221yp2k9pxJjFYXUul32a0t020IAsIdzt5jJsUNiYncM47zWPg4PaTLc19izfd+nsDvvK0ls7yCLbBTthLqg95BB4pDp2h8sqb6m40y247TcDHaYF3YQBGSP51UOsW9T5aG9tC22FtQCu4SgI3Bf9Kgyc/hFKx4iuJ5AgbbLK3MM+wFQu4D0rBIjPzmp8EnrdjmsubdN0OxSl1RdUYbc/LANd9LOVWWXsPpFYniHp+kSwzWHBIQJE3M2VYbV9TEAyTxnNabp2n09y0tx7O9mF5yS7z6HMLJmSRAHvBrNfR6FQGOnz5bPhn+JTkCT8RkY+RrDGnTnq3oXvJo041PTR/3Nz39RLHLSACrjaAJXgyAODTsPopchRBZdqtuBAgzndxP1OO3f36j1HSJczpljZaldiAbjDl+xGJG3g96x9J1DThnZLZguCFZEYBfwGOeOOK6uKvKleKf0ditH1a2Lp9lDLGoC8bljn25+ldM0nbI5798HA+dcw+ytwW1JXAJSAfx5FdQ0UwOO0/0rlr+v87FobGfRRFOsSTzFI8jB75nH0jvRtGPl8z2/fR37/wAPyoWJGtH4gu7bF9va1c//AFNborgjOfme/wA+1Vnxs+3R3z/oj9Yx/Gr01eSREtmcr6ZpLjJIu7FJkApv4kE/LiMfKjTdM1bKWXUEZmC7qCxZkweNxIOO0j3raeEujebBd2AIZgATACnbJE5JP7q2XU/DGl8piIJUiSsAiTE+nE57zVp8XTo8TKM5b9o7fLIjTc6ScVt7lF6x0t7G0u6tvLcEnK7Zknn4v31Z/CPSHu2VuK0KjMx9m3lrYBG4GJE9/hFazWdT06M9p9MpKG4gIA7So/aJmt50i+iWQPL2h1DKgJYKjRjccySGPt6q6+Js6Vm7e5jTvloLp3Qbty5c07MTsW2GeVJK2jdackzMjvmag3RLo1IsoxY3BcZTj0lzYXADRADe9O0t5Lr3C4Ft1CqoG4hhbTa2RiJ7e5r0cv5qXl9NtUaREsXZwY2nESB+qM1zNRUvUtvxmutthdW6ResXRLFkd7W0ZgNacboJJ5Kz7Ude6FqLNlnLk7UvKwEjN1Gdf0iMDAj37Ua0XbnllCPTdVrjcSqqxwI7icfOnri9xHRPUzCFmUAtsyiDjkCR+NRGMfIsl/PwG3roZT9B1OzzN7QWNzbmPJHo2xuiJIbiZ7d6xuk9Mv3LIYXHUOAqwD8cm4xBDDJDRUreomFkl4A5gG+oIJ+HAJzPyrH6fcFqytu+3rVQDAnByuY5AIxUctYvzLVjJ32KZ4hU+e4PbYM/K2gH7q1sVZeqajTrqH82yS396GzvG8j+6KjEQNoquWllgOQSBA5IntXrQ0ikc7ZsugShu3tygIgBm2Lkh3AACkjvXjfW253HUvPebMk//kq0dY6Nas2HS0pU3DaBkscb8c9+eK0+q8PKtrzBckxO0gj6j8K5K9WhGS5m72NacZyTx6GsFm3/AMUf/sH/ANSs/pVuWNq3qZa4rJm068qwMEPjBPuKwel6EXmgttExMTkzH7q2uh6aLGrtAMGwxn2PlsYNG+HVXl/5bi1THLoV8RtMjPvP0jH51n6DomqvnZasXGbnggR9WgVkdQ6MgWwLW4teiNxiZ7wBjPzNdP6Z1NbUgINygFzuOVIwfb371tVnKMfIrspFJvU5db6Pfs30t3rNxW3W+Oyludyz+/3q79XttptMSIZnYEhmKldpiPWc+4itzq9crP8A9lmQoKmSoPE9oNVvXdW0d4CyHdXVmZiskllkYlYAiuGuqlWKyXzroa02ou6Drlq82mF8bYFnaTbuexHJQxGSPzqqWBdA857zWkgIGVmJcAD02ln+IAqwNrbDaZ7SedIRllgCpFw4J295nJitZ1u7aNxtKbagIyKlyTNu0FAI28ZOfxrXhXjC72RWprIVp7dywWIZrdswov3bnqaP0VtiAQD7mBWHrtPpk27kKq4JW5adnGCVMpcAOCPet30fpdsJdXzGcFQYDMoVtrngHJ9K1PxN4dXz1AusF8m2QXLXDuYS2ew71r4ukoZ30I5Ussep7dA6xZ0dhEKm5ucxcthoY7mYW4BkH1ZBE4xWfb8Tae3JXTXRJ3EG3eH6TErM/DB75qr+EwU1R05yDJ+ly36lcexwR+NWbW2NXateY5GFbCgYJB2bvTxHuawrRpZq6vl7lo5W+DS6jqT2r1xreluMt0JCsHCggLJVSDkEYM1iaXqF3zLjLYuK0ruCyYgAAsIHqnM954rY+HNT1DVxtZET1AQg9TTuYiTjPJnvWx1PSNVb33QAWwMwogAKACpPsIJFV4udPDlaOXRN2LUYyUstbdz2+y1ybupwVnbg8jnmup6MYHHPf/rmuW/Zg7G9qSwg+mR7EE811PRA7RIE4+lUrq07fH7CGqM2iiisS1iFRXk8/wDXtTikue5oSTIrReItB51m5aP6S/tGa3kH3oZAealOzuiGrnG+na3UdOaDb3qJgjOCZII9pzS6r4xu3FK27USZkrAn3jvXS9b4asXZYFlJnjj8jWA3glP84/qiuh1KcpZSgrmajNKyehxC5ZcySCSZJJByTkk1cbLWyiRcGLaCN0EELBxV9Pgkf53/AJB/Oof2HH+cP1P604ipCvHGS/UU4yg7opt69aeAtwYJB9UcBR/Cmb9spsFxd3pn1e7Meat/9hf91f1P61E+Bj/mr+p/WsHGk5OVnqrb/wBF05JJdip271tQVNwbjuj1DssfxqOmuqjS9xQPSB6gclh/KrYfAx/zE/U/rUf7CP8A47f6lIwpJxdn5ff+iW5NP3KfYG197OoUFjMjjNR1Vve5IZSp25kcQKuJ8Cv/AI7X6tR/sK/+K1+rUculjjrvcZTvc5F4gO/UXSDI3mD78D+FYdoMpDDBBBB+YMiu0nwLc/2vy/pUf7CXP9r8v6V6K4yFrWOZ0pHPLesfUaa75zEAXLcbFzMyTH1isS84cFWv3iDz/dc/WK6hb8GX1wvlCeYkfwqZ8Jan3t/n/SqPiKbeqChNbHJdPZt25KXrgkQf7o5HzFZ/RbNrzgwuuzBXwbZA+A9zXSf7Jar/AG/z/pSPhHVf7ftz2/Kj4ine9tSVTnaxzGx4cuEKxuqg27gTMiCPy5r1TpGpubtupBXGS59Qj2ntXQG8C3j+hbMiPiPHtxUP7A3O1q1+f9Kt4qJHKkUodC1Q41YwYB3tH76XS109o3LTWvOvqr+oTtaeZ9+RV0bwHdOPKtx7bsT7xFRXwFeBlbaA+4Yg/nVJ14TVnctGnKLuUTpA1RF7ySiEWirLcX4rfcLPBFYmoQ6tRdSPNCgXE4LQIDr+EYrodzwFfbJtIfq5qKeAbqkEWEBHcPFVo1adO5acZSKF4c85WuIG27h6gQJPIxPHJqfiO5qHuKxuMzFQkDnavGF55ro6eFNT3tKfqwJ/Onc8KajtaUf+FgKh1lzMr6drDGWO2pzTQk6GbzQb7CFQ52qeWb5niszU+NdS6FTncIaSxBEQJz2q2v4Bckk2JJ77/wCteR+z9/8Ah/8Azj+daurRk02jPGojS+BOuWbIW3d9JUOAeJVzuwTwZq0dV61pBZZfNJLe8YEziOTWC3gJv+GP64/nXrpPAbhv/lwPmzA1zVqXC1KnMknc1hUqxjijy+zwO9/UajbtW4cT+NdO0i+nia1XRehGyIPOJjj6AVvEQBYj8KpVnnK5aEcVY9KKKKzLnnNJKKYoCVBpCjtQDXinURToBmgUs0UBKlRSoCS8UxUZomgGaFoooCVBpTSoCQopUTQDNAqJOKc0A6DSonFAMUUpomgBqBSmiaAdBomlNAOnUZomgBjTqJNE0BKk9KaJoAp0CigPJqkBUGNSmgGKGomg0BKilRNADUxSNE0A6TUTQaAYp0pomgJGikac0AUGiaRNAOilNMGgA0UE0TQDpNTmkTQDFFKaJoANApE0A0A6TU5pE0AxRSmgmgA0ClQDQDpGiigAU6QooDzYVIU6KAdRNFFASooooBNTp0UAqRoooCQpxRRQCNOiigCkaKKAcUUUUAGiiigCg0UUAUUUUAjTpUUA6RoooAiiKKKAVEUUUARRFFFAAooooD//2Q==

**Comment by KurtE** [comment]
I am guessing the above is some bitmap. 
Support for the Adafruit controller?

Sorry, I probably will not do the work to support it.   For the most part I have not touched any RC servos for a few years now.  Every once in awhile I look at my Phoenix or the like, but they all have SSC-32 servo controllers..

However if someone else wishes to create a motor driver file for it that works, I would be very happy to take a pull request to add the support to the library

**Comment by mano1979** [comment]
I see, i would do it myself but i just don't have the knowledge. i don't know wich parts i would have to remove/replace. 

I didn't find any clear code that whas meant to send a servo command.
